GET http://localhost:8080

###

POST http://localhost:8080/api/signin-login
Content-Type: application/json

{
  "username": "linerista",
  "password": "passer@123#"
}

###

POST http://localhost:8080/api/signin-phone
Content-Type: application/json

{
  "phone_number": "+22996111111"
}